import { getNoteTitle, type QuickNote } from '@/lib/researchStorage';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Escape characters that are special in BibTeX field values. */
function bbtEscape(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/[{}]/g, '\\$&')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_');
}

/** Derive the year string from an ISO date string, falling back to the note's createdAt. */
function getYear(iso: string | undefined, fallbackIso: string): string {
  const candidates = [iso, fallbackIso].filter(Boolean) as string[];
  for (const c of candidates) {
    const y = new Date(c).getFullYear();
    if (!isNaN(y)) return String(y);
  }
  return 'n.d.';
}

/** Build a BibTeX citation key from author, year, and title. */
function buildKey(author: string, year: string, title: string): string {
  const lastName = author
    ? (author.split(/[\s,]+/).filter(Boolean).pop() ?? author)
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '')
        .slice(0, 12)
    : 'anon';

  const titleWord = (title.split(/\s+/)[0] ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .slice(0, 10);

  return `${lastName}${year}_${titleWord}`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Format a single QuickNote as a BibTeX `@misc` entry.
 * The citation key is NOT deduplicated here; use `formatBibtexBundle`
 * when exporting multiple notes to get unique keys.
 */
export function formatBibtex(note: QuickNote, keyOverride?: string): string {
  const author = (note.metadata?.author ?? '').trim();
  const rawTitle = getNoteTitle(note);
  const title = bbtEscape(rawTitle);
  const year = getYear(note.metadata?.publishedDate, note.createdAt);
  const url = (note.metadata?.canonicalUrl || note.url || '').trim();
  const siteName = (note.metadata?.siteName ?? '').trim();
  const accessed = new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  }).format(new Date());

  const key = keyOverride ?? buildKey(author, year, rawTitle);

  // Build field list; only include non-empty fields
  const fields: string[] = [];
  if (author) fields.push(`  author       = {${bbtEscape(author)}}`);
  fields.push(`  title        = {${title}}`);
  if (siteName) fields.push(`  organization = {${bbtEscape(siteName)}}`);
  fields.push(`  year         = {${year}}`);
  if (url) {
    fields.push(`  url          = {${url}}`);
    fields.push(`  howpublished = {\\url{${url}}}`);
  }
  fields.push(`  note         = {Accessed: ${accessed}}`);

  return `@misc{${key},\n${fields.join(',\n')}\n}`;
}

/**
 * Format an array of QuickNotes as a `.bbt` file content string.
 * Duplicate citation keys are resolved by appending `_b`, `_c`, … suffixes.
 */
export function formatBibtexBundle(notes: QuickNote[]): string {
  const seen = new Map<string, number>();

  const entries = notes.map((note) => {
    const author = (note.metadata?.author ?? '').trim();
    const year = getYear(note.metadata?.publishedDate, note.createdAt);
    const base = buildKey(author, year, getNoteTitle(note));

    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);

    // First occurrence keeps the base key; subsequent ones get _b, _c, …
    const key = count === 0 ? base : `${base}_${String.fromCharCode(97 + count)}`;

    return formatBibtex(note, key);
  });

  const header = `% Generated by Øde — ${new Date().toISOString()}\n\n`;
  return header + entries.join('\n\n');
}
